export default [
  "What a beautiful day it is on the beach, here in beautiful and sunny Hawaii.",
  "Rex Quinfrey, a renowned scientist, created plans for an invisibility machine.",
  "Do you know why all those chemicals are so hazardous to the environment?",
  "You never did tell me how many copper pennies where in that jar; how come?",
  "Max Joykner sneakily drove his car around every corner looking for his dog.",
  "The two boys collected twigs outside, for over an hour, in the freezing cold!",
  "When do you think they will get back from their adventure in Cairo, Egypt?",
  "Trixie and Veronica, our two cats, just love to play with their pink ball of yarn.",
  "We climbed to the top of the mountain in just under two hours; isn’t that great?",
  "Hector quizzed Mr. Vexife for two hours, but he was unable to get any information.",
  "I have three things to do today: wash my car, call my mother, and feed my dog.",
  "Xavier Puvre counted eighty large boxes and sixteen small boxes stacked outside.",
  "The Reckson family decided to go to an amusement park on Wednesday.",
  "That herd of bison seems to be moving quickly; does that seem normal to you?",
  "All the grandfather clocks in that store were set at exactly 3 o’clock.",
  "There are so many places to go in Europe for a vacation Paris, Rome, Prague, etc.",
  "Those diamonds and rubies will make a beautiful piece of jewelry.",
  "The steamboats seemed to float down the Mississippi River at a snail’s pace.",
  "In order to keep up at that pace, Zack Squeve would have to work all night.",
  "A bird in the hand is worth two in the bush.",
  "Caught between a rock and a hard place.",
  "Closing the barn door after the horse escapes.",
  "Do I look like a turnip that just fell off the turnip truck?",
  "Don't count your chickens before they hatch.",
  "Don't make a mountain out of a molehill.",
  "Friends are flowers in the garden of life.",
  "The grass is always greener on the other side.",
  " Just staying one day ahead of yesterday.",
  "Lie down with dogs and wake up with fleas.",
  "The sharper the berry, the sweeter the wine.",
  "The squeaky wheel gets the grease.",
  "The stronger the breeze the stronger the trees.",
  "The way to a man's heart is through his stomach.",
  "A weed is no more than a flower in disguise.",
  "We'll cross that bridge when we come to it.",
  "You can lead a horse to water but you can't make him drink.",
  "You can't teach an old dog new tricks.",
  "All work and no play robs one of some fun in life.",
  "Your car is out of date as soon as it is paid for.",
];
